### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by GigaVik** [seniv/vk-tg-bot#10]
Привет, основные функции работают, все супер. Спасибо!
Только функция `/online` не работает почему то.

**Comment by seniv** [comment]
Странно, у меня никогда не было с ней проблем...
Есть какие-то ошибки в консоли, и что на эту команду отвечает бот?

**Comment by GigaVik** [comment]
Я сперва думал что он по команде `/online` выводит имена всех контактов в сети. Потом допер что он должен показывать статус выбранного контакта. Скажи пожалуйста как он его должен показывать?
И еще, когда запускал его у себя из под форточек, то вроде как при работе  бота видел что именно он делает. А сейчас поднял бота на виртуалке от амазон по SSH. И не могу сообразить как лог с него вытащить =( подскажи пожалуйста, хотябы наведи на информацию)

**Comment by BlackYuzia** [comment]
@seniv проверял /online, при этом был выбран "друг".
Словил следующее:

>ReferenceError: friend is not defined
    at vk.api.users.get.then (/home/kruzyapidor/kruzya/bot/kruzyapidor/tkbot.js:81:19)
    at tryCatcher (/home/kruzyapidor/kruzya/bot/kruzyapidor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kruzyapidor/kruzya/bot/kruzyapidor/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/kruzyapidor/kruzya/bot/kruzyapidor/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/kruzyapidor/kruzya/bot/kruzyapidor/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/kruzyapidor/kruzya/bot/kruzyapidor/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/kruzyapidor/kruzya/bot/kruzyapidor/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/kruzyapidor/kruzya/bot/kruzyapidor/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/kruzyapidor/kruzya/bot/kruzyapidor/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

**Comment by seniv** [comment]
https://github.com/seniv/vk-tg-bot/issues/14 Я тут написал несколько ответов на наши вопросы

**Comment by seniv** [comment]
@BlackYuzia, теперь проблема исправлена.
@GigaVik, теперь есть команда **/friendson** чтобы спотреть список друзей онлайн.
Подробнее сдесь https://github.com/seniv/vk-tg-bot/issues/14#issuecomment-392336672
