### ISSUE TITLE
[ERRORS] I get some errors 

### ISSUE THREAD

**Issue by BlackYuzia** [seniv/vk-tg-bot#15]
@seniv 
I get some errors. When you have time, check pls. Thanks.

>Failed to fetch updates. Waiting: 1s 500: Unsupported http response from Telegram
Failed to fetch updates. Waiting: 1s 500: Unsupported http response from Telegram
Failed to fetch updates. Waiting: 1s 500: Unsupported http response from Telegram
Failed to fetch updates. Waiting: 1s 500: Unsupported http response from Telegram
TypeError: Cannot read property 'length' of undefined
    at parseAttachments (/home/kruzyapidor/top-bot/tkbot.js:233:35)
    at app.telegram.sendMessage.then (/home/kruzyapidor/top-bot/tkbot.js:227:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'length' of undefined
    at parseAttachments (/home/kruzyapidor/top-bot/tkbot.js:233:35)
    at app.telegram.sendMessage.then (/home/kruzyapidor/top-bot/tkbot.js:227:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by seniv** [comment]
Попробуй сейчас, я обновил бота

**Comment by BlackYuzia** [comment]
@seniv 

> TypeError: VK is not a constructor
    at Object.<anonymous> (/home/yuzia/bots/vk/yuzia/tkbot.js:33:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
yuzia@vps39792938:~/bots/vk/yuzia$

**Comment by BlackYuzia** [comment]
После обновы. Словил.

**Comment by seniv** [comment]
Если всё еще есть проблемы - обнови NodeJS до версии 10+
