### ISSUE TITLE
error

### ISSUE THREAD

**Issue by panikajo** [seniv/vk-tg-bot#2]
at Promise._settlePromise (C:\vk-tg-bot-master\vk-tg-bot-master\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\vk-tg-bot-master\vk-tg-bot-master\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\vk-tg-bot-master\vk-tg-bot-master\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\vk-tg-bot-master\vk-tg-bot-master\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\vk-tg-bot-master\vk-tg-bot-master\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\vk-tg-bot-master\vk-tg-bot-master\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5) name: 'RequestError' }

**Comment by seniv** [comment]
@panikajo Как я понимаю у тебя нет доступа к серверам ВК. Используй ВПН или ставь на сервер.
И да, в следущий раз копируй ошибку полностью😉
