### ISSUE TITLE
[Error] Don't work after Update 

### ISSUE THREAD

**Issue by BlackYuzia** [seniv/vk-tg-bot#26]
@seniv поставил ласт...
~~Миша все херня. Давай сначала.~~
Чет все поломалось. :thinking: 

>Handle polling update error: TypeError: ctx.isInbox is not a function
    at vk.updates.on (/home/user/bots/tg_bot/tkbot.js:271:12)
    at use (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6586:61)
    at next (/home/user/bots/tg_bot/node_modules/middleware-io/lib/index.js:198:27)
    at Middleware.run (/home/user/bots/tg_bot/node_modules/middleware-io/lib/index.js:202:12)
    at Updates.dispatchMiddleware (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6966:28)
    at Updates.handlePollingUpdate (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6648:17)
    at Promise.all.response.updates.map (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6956:24)
    at Array.map (<anonymous>)
    at Updates.fetchUpdates (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6951:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Handle polling update error: TypeError: ctx.isInbox is not a function
    at vk.updates.on (/home/user/bots/tg_bot/tkbot.js:271:12)
    at use (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6586:61)
    at next (/home/user/bots/tg_bot/node_modules/middleware-io/lib/index.js:198:27)
    at Middleware.run (/home/user/bots/tg_bot/node_modules/middleware-io/lib/index.js:202:12)
    at Updates.dispatchMiddleware (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6966:28)
    at Updates.handlePollingUpdate (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6648:17)
    at Promise.all.response.updates.map (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6956:24)
    at Array.map (<anonymous>)
    at Updates.fetchUpdates (/home/user/bots/tg_bot/node_modules/vk-io/lib/index.js:6951:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by seniv** [comment]
Это точно ласт?
Файла `tkbot.js` больше нет, а у тебе он в логе ошибки)

**Comment by BlackYuzia** [comment]
А я по привычке закинул все в одно. :thinking: 
И запускал `tkbot.js` 

@seniv подскажи, как теперь это все запускать?

**Comment by BlackYuzia** [comment]
PS:  Инструкция не менялась. 
![image](https://user-images.githubusercontent.com/25010528/46949949-c8a3a700-d08b-11e8-9a05-77eee9756968.png)

**Comment by seniv** [comment]
Запускать через `npm start`. Инструкцию тоже обновил

**Comment by seniv** [comment]
И еще на всякий случай переустанови пикеты `npm install`

**Comment by BlackYuzia** [comment]
Succes
