### ISSUE TITLE
ctx.isInbox() is not a function

### ISSUE THREAD

**Issue by apepenkov** [seniv/vk-tg-bot#35]
ctx.isInbox() is not a function

**Comment by apepenkov** [comment]
Handle polling update error: TypeError: ctx.isInbox is not a function
    at vk.updates.on (/var/www/vk.apepenkov.ru/vk-tg-bot/src/vk.js:17:14)
    at use (/var/www/vk.apepenkov.ru/vk-tg-bot/node_modules/vk-io/lib/index.js:6865:61)
    at nextDispatch (/var/www/vk.apepenkov.ru/vk-tg-bot/node_modules/middleware-io/lib/index.js:31:40)
    at Updates.stackMiddleware (/var/www/vk.apepenkov.ru/vk-tg-bot/node_modules/middleware-io/lib/index.js:37:16)
    at Updates.dispatchMiddleware (/var/www/vk.apepenkov.ru/vk-tg-bot/node_modules/vk-io/lib/index.js:7242:17)
    at Updates.handlePollingUpdate (/var/www/vk.apepenkov.ru/vk-tg-bot/node_modules/vk-io/lib/index.js:6945:17)
    at response.updates.forEach (/var/www/vk.apepenkov.ru/vk-tg-bot/node_modules/vk-io/lib/index.js:7234:20)
    at Array.forEach (<anonymous>)
    at Updates.fetchUpdates (/var/www/vk.apepenkov.ru/vk-tg-bot/node_modules/vk-io/lib/index.js:7232:22)
    at <anonymous>
