### ISSUE TITLE
(node:32) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'link_ogg' of undefined

### ISSUE THREAD

**Issue by ghost** [seniv/vk-tg-bot#6]
(node:32) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'link_ogg' of undefined
    at parseAttachments (/home/psh/vk-tg-bot/tkbot.js:267:77)
    at app.telegram.sendMessage.then (/home/psh/vk-tg-bot/tkbot.js:255:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:32) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ghost** [comment]
ошибка видимо связана с сообщениями от групп.
